version: 2
submodules:
  include: all
build:
  os: ubuntu-20.04
  tools:
    python: '3.12'
  apt_packages:
    - libopenslide-dev
sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

